# Generated by Django 3.2.5 on 2021-07-26 21:20

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_session', '0003_trainingsession_required_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('required_materials', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Liste de materiel')),
                ('event_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True)),
                ('debriefing', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Debriefing')),
                ('is_canceled', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'training_plan',
                'verbose_name_plural': 'training_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanAttendersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('will_attend', models.BooleanField(default=True)),
                ('off_justified', models.BooleanField(default=True)),
                ('has_attended', models.BooleanField(default=False)),
                ('attender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_session_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_plan.trainingplan')),
            ],
            options={
                'unique_together': {('training_session_plan', 'attender')},
            },
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='attenders_list',
            field=models.ManyToManyField(through='training_plan.TrainingPlanAttendersList', to=settings.AUTH_USER_MODEL, verbose_name='Liste des participants'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='club.category', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='training_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_session.trainingsession', verbose_name='Session de référence'),
        ),
    ]
