# Generated by Django 3.2.5 on 2021-07-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='event_date',
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='start_time',
            field=models.DateTimeField(verbose_name='Heure de début'),
        ),
    ]
