# Generated by Django 3.2.5 on 2021-07-27 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plan', '0003_trainingplanattenderslist_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='start_time',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date et heure de début'),
        ),
    ]
