# Generated by Django 3.2.4 on 2021-06-08 21:36

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nom utilisateur')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address1', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Addresse ligne 1')),
                ('address2', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Addresse ligne 2')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ville')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Pays')),
                ('mobile_phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Entrer un code international pour mobile commençant par +(country code) par +336', regex='^\\+(?:[0-9]●?){6,14}[0-9]$')], verbose_name='Téléphone mobile')),
                ('phone_for_whatsapp', models.BooleanField(default=False, verbose_name='A utiliser pour WhatsApp')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Information complémentaires')),
                ('photo', models.ImageField(default='photos/default-user-avatar.png', upload_to='member_photos/', verbose_name='Photo du membre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_club_manager', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('involed_in_categories', models.ManyToManyField(blank=True, null=True, to='club.CategoryClubBySeason')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
