# Generated by Django 3.2.5 on 2021-07-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20210727_2146'),
        ('users', '0006_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='involed_in_categories',
        ),
        migrations.CreateModel(
            name='InvolvedAsICategoryForSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.TextField(default='Ajoutez ici la decription de la catégorie', null=True, verbose_name='Numéro de licence')),
                ('license_is_paid', models.BooleanField(default=False, verbose_name='License payée')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.category')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.season')),
            ],
            options={
                'unique_together': {('club', 'season', 'member', 'category', 'role')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='users.InvolvedAsICategoryForSeason', to='club.Category'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clubs',
            field=models.ManyToManyField(blank=True, null=True, through='users.InvolvedAsICategoryForSeason', to='club.Club'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, through='users.InvolvedAsICategoryForSeason', to='users.Role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seasons',
            field=models.ManyToManyField(blank=True, null=True, through='users.InvolvedAsICategoryForSeason', to='club.Season'),
        ),
    ]
