# Generated by Django 3.2.5 on 2021-07-29 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20210727_2146'),
        ('users', '0007_auto_20210729_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Saison'),
        ),
    ]
