# Generated by Django 3.2.5 on 2021-09-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210729_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='clubs',
            new_name='has_roles_in_categories_in_clubs',
        ),
        migrations.AddField(
            model_name='role',
            name='is_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='license_number',
            field=models.TextField(default='Non défine', null=True, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
