# Generated by Django 3.2.5 on 2021-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210903_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvedasicategoryforseason',
            name='is_player',
            field=models.BooleanField(default=True),
        ),
    ]
