# Generated by Django 3.2.5 on 2021-09-15 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20210727_2146'),
        ('users', '0010_involvedasicategoryforseason_is_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='involvedasicategoryforseason',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membre'),
        ),
    ]
