dist: bionic


language: python
python:
  - "3.8"

addons:
  # use chrome for Selenium 
  chrome: stable


branches:
  only:
      - develop

# stuff to do before executing the script
install:
    # command to install dependencies
  - pip install -r requirements.txt
  - pip install tchappui-webdrivers

before_script:
    # as URL set the url of the driver version supported on Travis 
  - wget https://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - psql -c 'create database travis_ci_test;' -U postgres


services:
    - postgresql


env: DJANGO_SETTINGS_MODULE="config.settings"


# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below