dist: bionic
language: python
python:
  - "3.8"

init:
    pip install pipenv
    pipenv install
    pipenv install --dev

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  ## using chrome and firefox for Selenium 
  chrome: stable
  firefox: latest


branches:
  only:
      - feature/continous
      - develop
      


install:
  pipenv install tchappui-webdrivers

before_script:
  - install-webdrivers --path /usr/local/bin/
  - psql -c 'create database pure;' -U postgres


services:
    - postgresql


env: DJANGO_SETTINGS_MODULE="config.settings"
global:
  - PGPORT=5433
  - PGUSER=travis
  - SECRET_KEY='elvisisNotDe@d' 
  - DATABASE='final'
  - USERAPP='travis'
  - PASSWORD='passw@rdMF'
  - DEBUG='True'
  

# command to run tests
script:
  - pytest --cov . # or py.test for Python versions 3.5 and below
  - flake8
