# Generated by Django 3.2.4 on 2021-07-06 20:32

import ckeditor_uploader.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
        ('practice', '0006_auto_20210601_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activé')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='club.Category', verbose_name='Liste des catégories')),
                ('practices', models.ManyToManyField(blank=True, null=True, to='practice.Practice', verbose_name='Liste des exercices')),
                ('skills', models.ManyToManyField(blank=True, null=True, to='practice.Skill', verbose_name='Liste des compétences')),
            ],
            options={
                'verbose_name': 'training_session',
                'verbose_name_plural': 'training_sessions',
            },
        ),
    ]
