# Generated by Django 3.2.2 on 2021-05-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Titre')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'practice',
                'verbose_name_plural': 'practices',
            },
        ),
    ]
