# Generated by Django 3.2.2 on 2021-05-21 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='practice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(default='Ajoutez ici la decription de la compétence visée'),
        ),
    ]
