# Generated by Django 3.2.2 on 2021-05-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
        ('practice', '0003_auto_20210521_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='categories',
            field=models.ManyToManyField(to='club.Category'),
        ),
        migrations.AddField(
            model_name='practice',
            name='skills',
            field=models.ManyToManyField(to='practice.Skill'),
        ),
    ]
