# Generated by Django 3.2.3 on 2021-05-28 11:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20210521_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
