# Generated by Django 3.2.3 on 2021-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
        ('practice', '0005_alter_practice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='categories',
            field=models.ManyToManyField(to='club.Category', verbose_name='Liste des catégories'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activé'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='skills',
            field=models.ManyToManyField(to='practice.Skill', verbose_name='Liste des compétences'),
        ),
    ]
