# Generated by Django 3.2.2 on 2021-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210517_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='club.Category'),
        ),
    ]
