# Generated by Django 3.2.2 on 2021-05-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_season_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='categories',
        ),
    ]
