# Generated by Django 3.2.2 on 2021-05-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_alter_season_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='label',
            field=models.CharField(max_length=128),
        ),
    ]
