# Generated by Django 3.2.5 on 2021-07-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_auto_20210520_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryclubbyseason',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='season',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='season',
            name='yob',
        ),
        migrations.RemoveField(
            model_name='season',
            name='yoe',
        ),
        migrations.AddField(
            model_name='season',
            name='beg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='description',
            field=models.TextField(default='Ajoutez ici la decription de la saison', null=True),
        ),
    ]
